import turtle
import math
#设置画布尺寸
turtle.screensize(400, 300, "#FFE4C4")
turtle.pensize(1)
turtle.pencolor("black")
turtle.speed(5)
turtle.hideturtle()
 
#画兔头
turtle.fillcolor("white")
turtle.begin_fill()
turtle.penup()
turtle.goto(0, 80)
turtle.seth(0)
turtle.pendown()
turtle.circle(-60, 90)
turtle.left(90)
turtle.circle(-25, 160)
turtle.circle(-200, 20)
turtle.goto(0, -40)
turtle.penup()
turtle.goto(0, 80)
turtle.seth(180)
turtle.pendown()
turtle.circle(60, 90)
turtle.right(90)
turtle.circle(25, 160)
turtle.circle(200, 20)
turtle.goto(0, -40)
turtle.end_fill()
 
#画兔嘴巴
turtle.penup()
turtle.goto(0, 0)
turtle.right(60)
turtle.pendown()
turtle.circle(10, 135)
turtle.penup()
turtle.goto(0, 0)
turtle.seth(0)
turtle.pendown()
turtle.right(120)
turtle.circle(-10, 135)
turtle.penup()
turtle.seth(0)
turtle.goto(-10, -5)
turtle.pendown()
turtle.right(90)
turtle.fillcolor("pink")
turtle.begin_fill()
turtle.forward(5)
turtle.circle(10, 180)
turtle.forward(5)
 
#画兔鼻子
turtle.penup()
turtle.seth(0)
turtle.goto(0, 0)
turtle.pendown()
turtle.circle(3)
turtle.end_fill()
 
#画兔眼睛
#左眼
turtle.penup()
turtle.seth(0)
turtle.goto(-35, 5)
turtle.pendown()
turtle.fillcolor("white")
turtle.begin_fill()
turtle.circle(12)
turtle.end_fill()
turtle.fillcolor("black")
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
#右眼
turtle.penup()
turtle.seth(0)
turtle.goto(35, 5)
turtle.pendown()
turtle.fillcolor("white")
turtle.begin_fill()
turtle.circle(12)
turtle.end_fill()
turtle.fillcolor("black")
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
 
#画兔耳朵
turtle.penup()  # 左耳
turtle.seth(90)
x1 = -5
y1 = math.sqrt(80**2-x1**2)
x2 = -20
y2 = math.sqrt(80**2-x2**2)
x3 = -10
y3 = math.sqrt(80**2-x3**2)
x4 = -15
y4 = math.sqrt(80**2-x4**2)
turtle.goto(x1, y1)
turtle.pendown()
turtle.fillcolor("white")
turtle.begin_fill()
turtle.circle(100, 30)
turtle.circle(15, 180)
turtle.goto(x2, y2)
turtle.end_fill()
turtle.fillcolor("pink")  # 左耳上色
turtle.penup()
turtle.seth(90)
turtle.goto(x3, y4)
turtle.pendown()
turtle.begin_fill()
turtle.circle(100, 20)
turtle.circle(8, 180)
turtle.goto(x4, y4)
turtle.end_fill()
turtle.penup()  # 右耳
turtle.seth(90)
x5 = 5
y5 = math.sqrt(80**2-x5**2)
x6 = 20
y6 = math.sqrt(80**2-x6**2)
x7 = 10
y7 = math.sqrt(80**2-x7**2)
x8 = 15
y8 = math.sqrt(80**2-x8**2)
turtle.goto(x5, y5)
turtle.pendown()
turtle.fillcolor("white")
turtle.begin_fill()
turtle.circle(-100, 30)
turtle.circle(-15, 180)
turtle.goto(x6, y6)
turtle.end_fill()
turtle.fillcolor("pink")  # 右耳上色
turtle.penup()
turtle.seth(90)
turtle.goto(x7, y7)
turtle.pendown()
turtle.begin_fill()
turtle.circle(-100, 20)
turtle.circle(-8, 180)
turtle.goto(x8, y8)
turtle.end_fill()
 
#画兔身
turtle.fillcolor("white")
turtle.penup()  # 左边
turtle.seth(180)
turtle.goto(0, -40)
turtle.begin_fill()
turtle.pendown()
turtle.circle(-200, 15)
turtle.seth(-135)
turtle.circle(100, 25)
turtle.circle(60, 90)
turtle.goto(0, -150)
turtle.penup()  # 右边
turtle.seth(0)
turtle.goto(0, -40)
turtle.pendown()
turtle.circle(200, 15)
turtle.seth(-45)
turtle.circle(-100, 25)
turtle.circle(-60, 90)
turtle.goto(0, -150)
turtle.end_fill()
 
#画兔手和脚
turtle.fillcolor("white")
turtle.penup()  # 左手
turtle.seth(0)
turtle.goto(-50, -40)
turtle.begin_fill()
turtle.pendown()
turtle.forward(8)
turtle.circle(-15, 180)
turtle.forward(8)
turtle.circle(-15, 180)
turtle.penup()  # 右手
turtle.seth(180)
turtle.goto(50, -40)
turtle.pendown()
turtle.forward(8)
turtle.circle(15, 180)
turtle.forward(8)
turtle.circle(15, 180)
turtle.end_fill()
turtle.fillcolor("white")
turtle.penup()  # 左脚
turtle.seth(135)
turtle.goto(-50, -150)
turtle.begin_fill()
turtle.pendown()
turtle.forward(12)
turtle.circle(-15, 180)
turtle.forward(12)
turtle.circle(-15, 180)
turtle.penup()  # 右脚
turtle.seth(45)
turtle.goto(50, -150)
turtle.pendown()
turtle.forward(12)
turtle.circle(15, 180)
turtle.forward(12)
turtle.circle(15, 180)
turtle.end_fill()
 
#福字
turtle.fillcolor("#CD4F39")  # 红纸
turtle.penup()
turtle.seth(-45)
turtle.begin_fill()
turtle.goto(0, -30)
turtle.pendown()
i = 1
for i in range(4):
    turtle.forward(90)
    turtle.right(90)
    i = i+1
turtle.end_fill()
turtle.pencolor("#FFDE00")  # 金字
turtle.pensize(6)
turtle.penup()  # 点
turtle.goto(-21, -70)
turtle.seth(-60)
turtle.pendown()
turtle.forward(8)
turtle.penup()  # 横折
turtle.goto(-30, -80)
turtle.seth(0)
turtle.pendown()
turtle.forward(20)
turtle.right(145)
turtle.forward(35)
turtle.penup()  # 竖
turtle.goto(-20, -90)
turtle.seth(-90)
turtle.pendown()
turtle.forward(38)
turtle.penup()  # 点
turtle.goto(-20, -90)
turtle.seth(-45)
turtle.pendown()
turtle.forward(10)
turtle.penup()  # 横
turtle.goto(0, -75)
turtle.seth(0)
turtle.pendown()
turtle.forward(25)
turtle.penup()  # 口
turtle.goto(2, -85)
turtle.seth(-90)
turtle.pendown()
turtle.forward(10)
turtle.penup()
turtle.goto(2, -85)
turtle.seth(0)
turtle.pendown()
turtle.forward(18)
turtle.right(100)
turtle.forward(10)
turtle.penup()
turtle.goto(2, -95)
turtle.seth(0)
turtle.pendown()
turtle.forward(15)
turtle.penup()  # 田
turtle.goto(-3, -105)
turtle.seth(-90)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.goto(-3, -105)
turtle.seth(0)
turtle.pendown()
turtle.forward(30)
turtle.right(100)
turtle.forward(22)
turtle.penup()
turtle.goto(-3, -115)
turtle.seth(0)
turtle.pendown()
turtle.forward(25)
turtle.penup()
turtle.goto(10, -105)
turtle.seth(-90)
turtle.pendown()
turtle.forward(15)
turtle.penup()
turtle.goto(0, -125)
turtle.seth(0)
turtle.pendown()
turtle.forward(25)
 
turtle.done()